"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-09-26 12:30:56.257272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=False),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('programmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('grade_range', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('option_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('max_choices_per_student', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programme_id', 'grade', 'name', name='uq_block')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('condition_json', sa.Text(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_rule_type'), ['rule_type'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('cohort_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('language_profile', sa.String(length=200), nullable=False),
    sa.Column('prior_subjects', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_student_id'), ['student_id'], unique=True)

    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('ib_group', sa.Integer(), nullable=False),
    sa.Column('offered_levels', sa.String(length=10), nullable=False),
    sa.Column('prerequisites', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_code'), ['code'], unique=True)

    op.create_table('student_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_preferences_student_id'), ['student_id'], unique=False)

    op.create_table('subject_offerings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=2), nullable=False),
    sa.Column('teacher', sa.String(length=100), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_enrollment', sa.Integer(), nullable=False),
    sa.Column('min_enrollment', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['option_blocks.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'block_id', 'level', name='uq_offering')
    )
    op.create_table('change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('current_offering_id', sa.Integer(), nullable=False),
    sa.Column('requested_offering_id', sa.Integer(), nullable=False),
    sa.Column('compensating_current_offering_id', sa.Integer(), nullable=True),
    sa.Column('compensating_requested_offering_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('feasibility_status', sa.String(length=30), nullable=True),
    sa.Column('feasibility_reasons_json', sa.Text(), nullable=False),
    sa.Column('override_by', sa.String(length=100), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compensating_current_offering_id'], ['subject_offerings.id'], ),
    sa.ForeignKeyConstraint(['compensating_requested_offering_id'], ['subject_offerings.id'], ),
    sa.ForeignKeyConstraint(['current_offering_id'], ['subject_offerings.id'], ),
    sa.ForeignKeyConstraint(['requested_offering_id'], ['subject_offerings.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_requests_student_id'), ['student_id'], unique=False)

    op.create_table('student_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['subject_offerings.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_choices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_choices_offering_id'), ['offering_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_choices_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_choices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_choices_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_choices_offering_id'))

    op.drop_table('student_choices')
    with op.batch_alter_table('change_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_requests_student_id'))
        batch_op.drop_index(batch_op.f('ix_change_requests_status'))

    op.drop_table('change_requests')
    op.drop_table('subject_offerings')
    with op.batch_alter_table('student_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_preferences_student_id'))

    op.drop_table('student_preferences')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_code'))

    op.drop_table('subjects')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_student_id'))
        batch_op.drop_index(batch_op.f('ix_students_status'))

    op.drop_table('students')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_rule_type'))

    op.drop_table('rules')
    op.drop_table('option_blocks')
    op.drop_table('users')
    op.drop_table('programmes')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
